config/routes.rb
Rshim::Application.routes.draw do
  resources :security_types

  resources :sources

  resources :localities

  resources :currencies

  resources :bars, :currencies, :localities

  root :to => "home#index"

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  set_table_name 'Locality'
  set_primary_key 'icc'
  alias_attribute :country, :text
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @localities }
    end
  end

=begin
The scaffolding is all reference by ID and does not work here.
 
  # GET /localities/1
  # GET /localities/1.json
  def show
    @locality = Locality.find(params[:icc])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /localities/new
  # GET /localities/new.json
  def new
    @locality = Locality.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /localities/1/edit
  def edit
    @locality = Locality.find(params[:id])
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(params[:locality])

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render json: @locality, status: :created, location: @locality }
      else
        format.html { render action: "new" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /localities/1
  # PUT /localities/1.json
  def update
    @locality = Locality.find(params[:id])

    respond_to do |format|
      if @locality.update_attributes(params[:locality])
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality = Locality.find(params[:id])
    @locality.destroy

    respond_to do |format|
      format.html { redirect_to localities_url }
      format.json { head :ok }
    end
  end
=end  

end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_for(@locality) do |f| %>
  <% if @locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% @locality.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icc %><br />
    <%= f.text_field :icc %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing locality</h1>

<%= render 'form' %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', localities_path %>

app/views/localities/index.html.erb
<h1>Listing localities</h1>

<table>
  <tr>
    <th>Icc</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @localities.each do |locality| %>
  <tr>
    <td><%= locality.icc %></td>
    <td><%= locality.country %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_url %>

app/views/localities/new.html.erb
<h1>New locality</h1>

<%= render 'form' %>

<%= link_to 'Back', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Icc:</b>
  <%= @locality.icc %>
</p>

<p>
  <b>Text:</b>
  <%= @locality.text %>
</p>


<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %>