config/routes.rb
Rshim::Application.routes.draw do
  resources :security_types

  resources :sources

  resources :localities

  resources :currencies

  resources :bars, :currencies, :localities

  root :to => "home#index"

end

app/controllers/security_types_controller.rb
class SecurityTypesController < ApplicationController
  # GET /security_types
  # GET /security_types.json
  def index
    @security_types = SecurityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @security_types }
    end
  end

=begin
The scaffolding is all reference by ID and does not work here.

  # GET /security_types/1
  # GET /security_types/1.json
  def show
    @security_type = SecurityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @security_type }
    end
  end

  # GET /security_types/new
  # GET /security_types/new.json
  def new
    @security_type = SecurityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @security_type }
    end
  end

  # GET /security_types/1/edit
  def edit
    @security_type = SecurityType.find(params[:id])
  end

  # POST /security_types
  # POST /security_types.json
  def create
    @security_type = SecurityType.new(params[:security_type])

    respond_to do |format|
      if @security_type.save
        format.html { redirect_to @security_type, notice: 'Security type was successfully created.' }
        format.json { render json: @security_type, status: :created, location: @security_type }
      else
        format.html { render action: "new" }
        format.json { render json: @security_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /security_types/1
  # PUT /security_types/1.json
  def update
    @security_type = SecurityType.find(params[:id])

    respond_to do |format|
      if @security_type.update_attributes(params[:security_type])
        format.html { redirect_to @security_type, notice: 'Security type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @security_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /security_types/1
  # DELETE /security_types/1.json
  def destroy
    @security_type = SecurityType.find(params[:id])
    @security_type.destroy

    respond_to do |format|
      format.html { redirect_to security_types_url }
      format.json { head :ok }
    end
  end
=end

end

app/helpers/security_types_helper.rb
module SecurityTypesHelper
end

app/views/security_types/_form.html.erb
<%= form_for(@security_type) do |f| %>
  <% if @security_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@security_type.errors.count, "error") %> prohibited this security_type from being saved:</h2>

      <ul>
      <% @security_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.number_field :uid %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :test %><br />
    <%= f.text_field :test %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/security_types/edit.html.erb
<h1>Editing security_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @security_type %> |
<%= link_to 'Back', security_types_path %>

app/views/security_types/index.html.erb
<h1>Listing security_types</h1>

<table>
  <tr>
    <th>Uid</th>
    <th>Type</th>
    <th>IB_Text</th>
    <th>Label</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @security_types.each do |security_type| %>
  <tr>
    <td><%= security_type.uid %></td>
    <td><%= security_type.ib_text %></td>
    <td><%= security_type.security_type %></td>
    <td><%= security_type.label %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_url %>

app/views/security_types/new.html.erb
<h1>New security_type</h1>

<%= render 'form' %>

<%= link_to 'Back', security_types_path %>

app/views/security_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @security_type.uid %>
</p>

<p>
  <b>Type:</b>
  <%= @security_type.type %>
</p>

<p>
  <b>Test:</b>
  <%= @security_type.test %>
</p>

<p>
  <b>Lable:</b>
  <%= @security_type.label %>
</p>


<%= link_to 'Edit', edit_security_type_path(@security_type) %> |
<%= link_to 'Back', security_types_path %>