config/routes.rb
Rshim::Application.routes.draw do
  resources :security_types

  resources :sources

  resources :localities

  resources :currencies

  resources :bars, :currencies, :localities

  root :to => "home#index"

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  set_table_name 'Currency'
  set_primary_key 'code'
  belongs_to :locality, :foreign_key => 'icc'
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

=begin
The scaffolding is all reference by ID and does not work here.

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :ok }
    end
  end
=end
  
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :icc %><br />
    <%= f.text_field :icc %>
  </div>
  <div class="field">
    <%= f.label :plural %><br />
    <%= f.text_field :plural %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Icc</th>
    <th>Plural</th>
    <th>Country</th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.code %></td>
    <td><%= currency.icc %></td>
    <td><%= currency.plural %></td>
    <td><%= currency.locality.country %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_url %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @currency.code %>
</p>

<p>
  <b>Icc:</b>
  <%= @currency.icc %>
</p>

<p>
  <b>Plural:</b>
  <%= @currency.plural %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>