config/routes.rb
Rshim::Application.routes.draw do
  resources :security_types

  resources :sources

  resources :localities

  resources :currencies

  resources :bars, :currencies, :localities

  root :to => "home#index"

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  set_table_name 'BarSize'
  set_primary_key 'uid'
  set_inheritance_column :bar_type

  # getter for the "type" column
  def bar_type
   self[:type]
  end

  # setter for the "type" column
  def bar_type=(s)
  self[:type] = s
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

=begin
The scaffolding is all reference by ID and does not work here.

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :ok }
    end
  end
=end
  
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<h1>Listing bars</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Text</th>
  </tr>

<% @bars.each do |bar| %>
  <tr>
    <td><%=h bar.bar_type %></td>
    <td><%=h bar.text %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_url %>

app/views/bars/new.html.erb
<h1>New bar</h1>

<%= render 'form' %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bar_path(@bar) %> |
<%= link_to 'Back', bars_path %>